version: '2'
services:   
  autonode:
    build: .
    image: ghcr.io/constructiverealities/cr-dai-tools/build:develop
    network_mode: host
    command: /opt/ros/noetic/bin/depthai-daemon /opt/ros/noetic/bin/autonode
    privileged: true
    devices:
      - '/dev:/dev'
    volumes:
      - '/dev:/dev'
      - '~/.local/share/cr-dai-tools:/root/.local/share/cr-dai-tools'      
    environment:
      - DEPTHAI_LEVEL="debug"
      - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    restart: on-failure
  ui:
    image: osrf/ros:noetic-desktop-full
    network_mode: host
    environment:
      - 'DISPLAY=${DISPLAY}'
    volumes:
      - '/tmp/.X11-unix:/tmp/.X11-unix'
      - '~/.Xauthority:/root/.Xauthority'
      - './perspectives:/host/perspectives'
    command: rosrun rqt_gui rqt_gui --perspective-file /host/perspectives/Default.perspective
  opencv-ui:
    build: .
    image: ghcr.io/constructiverealities/cr-dai-tools/build:develop
    network_mode: host
    environment:
      - 'DISPLAY=${DISPLAY}'
    volumes:
      - '/tmp/.X11-unix:/tmp/.X11-unix'
      - '~/.Xauthority:/root/.Xauthority'
    command: /opt/ros/noetic/bin/depthai-daemon /opt/ros/noetic/bin/example-ui
  roscore:
    image: osrf/ros:noetic-desktop-full
    network_mode: host
    command: roscore
  demo:
    extends: autonode
    depends_on:
      - roscore
      - ui
