name: Create and publish a Docker image

on:
  push:
    branches: ['develop']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_NAME_ROS2: ${{ github.repository }}-ROS2

jobs:
  build-and-push-release:
    runs-on: windows-2019
    permissions:
      contents: read
      packages: write

    steps:
      - uses: ros-tooling/setup-ros@v0.3
        with:
          required-ros-distributions: foxy
      - uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: source add -n=ros-win -s="https://aka.ms/ros/public" --priority=1
      - uses: ros-tooling/action-ros-ci@v0.2
        with:
          target-ros2-distro: foxy
          package-name: cr-dai-tools
          extra-cmake-args: -DROS_BUILD=ON
          vcs-repo-file-url: https://raw.githubusercontent.com/ros2/ros2/foxy/ros2.repos
          colcon-defaults: |
            {
              "build": {            
                "cmake-args": [
                    "-DBUILD_DEPTHAI=ON"
                ]
              }
            }

  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Extract metadata (tags, labels) for Docker (ROS2)
        id: meta_ros2
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_ROS2 }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push Docker image (ROS2)
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: Dockerfile.ros2
          push: true
          tags: ${{ steps.meta_ros2.outputs.tags }}
          labels: ${{ steps.meta_ros2.outputs.labels }}
